from pathlib import Path

p = Path('README.md')
s = p.read_text()

# Remove examples from structure block
s = s.replace("\n\u251c\u2500 examples/\n\u2502  \u2514\u2500 external-host.html  # Example of embedding on a 3rd\u2011party page\n","\n")
# Remove optional Python server line
s = s.replace("- (Optional) Python 3 for a quick local static server\n","")
# Remove the local example section
s = s.replace(
    "3) Run the included external example locally\n- Start a static server from the repo root (choose one):\n```bash\n# Recommended (Python built\u2011in)\npython3 -m http.server 8080\n```\n- Open the example page:\n```\nhttp://localhost:8080/host_website/index.html\n```\n\nYou should see a button on the page; click it to open the centered overlay widget.\n\n",
    ""
)
# Simplify testing section
s = s.replace(
    "## Testing locally and linting\n- Build: `npm run build`\n- Open example: `host_website/index.html` via a static server (see above)\n- Lint: `npm run lint`\n",
    "## Testing locally and linting\n- Build: `npm run build`\n- Lint: `npm run lint`\n"
)
# Remove serve lines in release tips
s = s.replace(
    "# optional: serve locally and test\npython3 -m http.server 8080\n# visit http://localhost:8080/host_website/index.html\n",
    ""
)
# Pages: update what is published
s = s.replace(
    "What is published to Pages\n- `dist/chat-widget.js` (the embeddable bundle)\n- `host_website/index.html` (demo page)\n",
    "What is published to Pages\n- `dist/chat-widget.js` (the embeddable bundle)\n- `index.html` (minimal demo generated by the workflow)\n"
)
# Pages: update flow step
s = s.replace(
    "1) Develop locally: `npm run build`, test `host_website/index.html`",
    "1) Develop locally: `npm run build`"
)
# Remove example page URLs and any remaining host_website mentions
s = s.replace(
    "  - Example page: https://caretapps-developer.github.io/ms-chat-widget-iffe/host_website/index.html\n",
    ""
)
s = s.replace("host_website/index.html","index.html")

p.write_text(s)
print("Patched README.md")

