name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Attach bundle to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/chat-widget.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

